# %% [code]
---
title: "Housing Prices Regression"
author: "Zhiwei Lin"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
```{r}
library(tidyverse)
library(caret)
library(glmnet)
```

### Import data
```{r}
train<- read_csv("/kaggle/input/house-prices-advanced-regression-techniques/train.csv")
test <- read_csv("/kaggle/input/house-prices-advanced-regression-techniques/test.csv")
```

```{r}
head(train)
```

```{r}
test$Id <- NULL
train$Id <- NULL
test$SalePrice <- NA
```
Remove id variable in both data and add SalePrice variable to test_data

```{r}
all <- rbind(train,test)
```
combine train and test data

```{r}
missing_percentage <- function(df){
 colSums(is.na(df))/nrow(df)
}
missing_percentage(all)
```

```{r}
all <- mutate_if(all,is.character,as.factor)
```

```{r}
all <- all %>% mutate_if(is.factor, ~ ifelse(is.na(.), 0, .))
# replace missing values NA with 0 for all categorical variables
all <- all %>% mutate_if(is.numeric, ~ ifelse(is.na(.), mean(., na.rm = TRUE), .))
# replcae missing values NA with mean for all numeric variables
sum(is.na(all))
# no missing values in the data anymore

```


```{r}
# Split the data back to training and test sets
train_data <- all[1:nrow(train),]
test_data <- all[(nrow(train)+1):nrow(all),]
test_data$SalePrice <- NA
```

### Ridge regression
```{r}
lambda <- 10^seq(-3, 3, length = 100)
```

```{r}
# Build the model
set.seed(123)
ridge <- train(
  SalePrice ~., data = train_data, method = "glmnet",
  trControl = trainControl("cv", number = 10),
  tuneGrid = expand.grid(alpha = 0, lambda = lambda)
  )
```

```{r}
# Model coefficients
coef(ridge$finalModel, ridge$bestTune$lambda)
```

```{r}
# Make predictions
ridge_predictions <- ridge %>% predict(test_data)
ridge_predictions <- list(unname(ridge_predictions))[[1]]
head(ridge_predictions)
```

### Lasso regression
```{r}
# Build the model
set.seed(123)
lasso <- train(
  SalePrice ~., data = train_data, method = "glmnet",
  trControl = trainControl("cv", number = 10),
  tuneGrid = expand.grid(alpha = 1, lambda = lambda)
  )

```

```{r}
# Model coefficients
coef(lasso$finalModel, lasso$bestTune$lambda)
```

```{r}
# Make predictions
lasso_predictions <- lasso %>% predict(test_data)
lasso_predictions <- list(unname(lasso_predictions))[[1]]
head(lasso_predictions)
```



### elastic net regession
```{r}
# Build the model using the training set
set.seed(123)
elastic <- train(
  SalePrice ~., data = train_data, method = "glmnet",
  trControl = trainControl("cv", number = 10),
  tuneLength = 10
  )
```

```{r}
# Model coefficients
coef(elastic$finalModel, elastic$bestTune$lambda)
```

```{r}
# Make predictions
elastic_predictions <- elastic %>% predict(test_data)
elastic_predictions <- list(unname(elastic_predictions))[[1]]
head(elastic_predictions)
```

### Comparing models
```{r}
models <- list(ridge = ridge, lasso = lasso, elastic = elastic)
resamples(models) %>% summary( metric = "RMSE")
```




